---
- hosts: all
  tasks:
    - name: creates users files
      file:
        path: /tmp/ansible-{{ item }}
        state: touch
      loop:
        - Oxymoron
        - Zenith
        - Terebinth
        - Aphorism
        - Amutabi
        - Lomalinda
