---
- hosts: all
  tasks:
  # - name: add the /etc/yum.repos.d/epel.repo
  #   yum_repository:
  #     name: epel
  #     description: EPEL repo
  #     baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

  # - name: update wget
  #   dnf:
  #     name: wget
  #     state: latest
#Assume multiple packages are to be updated at the same time. The set up would look as follows.
# - name: update wget and bzip2
#   dnf:
#     name: ['wget', 'bzip2']
#     state: latest

  - name: update all packages # This is equivalent to running the 'dnf update' command
    dnf:
      name: "*"
      state: latest
# some package updates might require update. In such cases, the following task need to be active and run too.
#   - name: reboot the OS
#     reboot:
#       msg: "Reboot initiated by Ansible"
#       connect_timeout: 5
#       reboot_timeout: 600
#       pre_reboot_delay: 0
#       post_reboot_delay: 30
#       test_command: whoami
#     become: yes
