---
- name: harden linux systems
  hosts: all
  become: true
  vars:
    - harden_firewall: false

  tasks:
    - name: Configure firewall
      when: harden_firewall | bool
      include_role:
        name: linux-system-roles.firewall

    - name: Configure Timesync
      when: harden_time | bool
      include_role:
        name: redhat.rhel_system_roles.timesync
