---
vcenter_hostname: "vmware.example.com"
vcenter_datacenter: "dc_vmware"
vcenter_validate_certs: false
vcenter_username: "theUser@vsphere.local"
vcenter_password: "m1ssi0nPossibl3#"
vm_name: "mboya_workbench"
vm_guestid: "centos64Guest"
vm_disk_gb: 10
vm_disk_type: "thin"
vm_disk_datastore: "Datastore-1"
vm_hw_ram_mb: 1024
vm_hw_cpu_n: 1
vm_hw_scsi: "paravirtual"
vm_net_name: "VM Network"
vm_net_type: "vmxnet3"
vcenter_destination_folder: "mboya_workbench"
vm_state: "poweroff"
